### ISSUE TITLE
Benutzung unseres Codes

### ISSUE THREAD

**Issue by ilouHD** [MeinerLP1/CloudSystemTestWeb#4]
Hallo,

durch Zufall bin ich soeben auf Ihr Projekt aufmerksam geworden. Bei Ihrem Projekt handelt es sich augenscheinlich um ein Cloudsystem für Minecraft, welches auf dem Quellcode eines unserer entsprechenden Projekte basiert.

Das Projekt, um welches es sich handelt ist folgendes: https://github.com/MinecraftCloudSystem

Grundsätzlich stellt die Verwendung unseres Codes keinerlei Verstoß gegen die geltende Lizenz dar, allerdings gibt es einige Unstimmigkeiten Ihres Projektes mit unserem:
- Wir entwickeln unser System unter der AGPL-Lizenz, das bedeutet Sie müssen, sofern Sie unseren Quellcode nutzen wollen, die selbe Lizenz nutzen
- Die AGPL-Lizenz sieht eine Erwähnung des ursprünglichen Entwicklers vor. Da die Organisation MinecraftCloudSystem zur NodeLab IT ( https://github.com/NodeLabIT sowie https://nodelab-it.de ) gehört, bzw. in diese Übergegangen ist, ist eine Erwähnung unseres Unternehmen in ihrem Quellcode nötig. Alternativ sind Sie dazu verpflichtet, unseren Quellcode aus Ihrem Projekt zu entfernen.

Mit freundlichen Grüßen
ilou
NodeLab IT

**Comment by MeinerLP1** [comment]
Hallo, die Annahme von ihnen ist falsch da es sich um eine selbst entwickeltes Projekt Handel was auf Tutorials basiert. Wie man auch lesen kann ist das nur eine Test/Preview zum endgültigen System.

**Comment by MeinerLP1** [comment]
Die Firma hat keine Impressum, somit ist ihr Lizenzen Erwähnung nicht gültig!

**Comment by ilouHD** [comment]
Inwiefern hat die Webseite kein Impressum? Das Impressum ist hier zu finden: https://nodelab-it.de/imprint

Und bzgl. der Annahme: Wieso ist der Code von Ihnen dann zu 99% gleich zu dem aus unserem Projekt? Sogar die Variablen heißen größtenteils gleich.

**Comment by MeinerLP1** [comment]
Zu diesem Zeitpunkt als ich das Impressum von ihnen anblickte war von ihnen das Impressum in eine Muster vorgabe. Ich werde mich bezüglich des Codes am Sonntag an eignen und ändern das ihre Lizenz nicht mehr in Kraft treten kann

**Comment by ilouHD** [comment]
Ich habe zwar nichts an der Webseite geändert - außer der Installation eines Sicherheitspatch, der allerdings nur das Control Panel betrifft.
Möglich wäre, dass der SQL-Server kurze zeit nicht erreichbar war.

Vielen Dank für Ihre Einsicht und der Bemühung, Ihren Quellcode anzupassen.

**Comment by ilouHD** [comment]
Bitte ändern Sie in den nächsten 5 Tagen Ihren Quellcode ab oder löschen Sie diesen.
